### ISSUE TITLE
Port new ca correction code from rt as soon as it is in dev branch of rt

### ISSUE THREAD

**Issue by heckflosse** [CarVac/librtprocess#11]
Todo for 1.0

**Comment by heckflosse** [comment]
@CarVac @aferrero2707 

To port the new ca correction code from rt I need to include the gauss code (two source files) as well.
I can do that in a way that it is just used internally in raw ca correction without exposing the gauss interface, but I can also do that with exposing the gauss interface. The latter would mean, the highly optimized gauss functions from rt would be also available for projects which use librtprocess.

What do you prefer?

**Comment by CarVac** [comment]
Gauss functions as in gaussian blur?

**Comment by heckflosse** [comment]
@CarVac Yes, exactly this file https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/gauss.h and also this https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/gauss.cc

**Comment by CarVac** [comment]
I'm fine with exposing functionality.

**Comment by heckflosse** [comment]
see https://github.com/CarVac/librtprocess/pull/13
