### ISSUE TITLE
mac clang conversion error

### ISSUE THREAD

**Issue by Benitoite** [CarVac/librtprocess#16]
Compiling on mac with clang++-mp-3.9.1
```
/Users/tune/librtprocess/src/include/boxblur.h:40:12: error: no viable conversion from 'JaggedArray<float>' to 'float *'
    float* temp = buffer;
           ^      ~~~~~~

```
I tried:
    float* temp = *buffer;
which does compile.

**Comment by heckflosse** [comment]
@Benitoite I will take a look

**Comment by heckflosse** [comment]
@Benitoite Does this fix it?

https://github.com/heckflosse/librtprocess/commit/10d586853d8ebed3da1af8a2fee26831f7aa6b80

**Comment by CarVac** [comment]
I merged @heckflosse 's pull request.
