### ISSUE TITLE
don't duplicate

### ISSUE THREAD

**Issue by aurelienpierre** [CarVac/librtprocess#28]
You might want to have a look at that project and not duplicate it: https://github.com/halide/Halide

The main problem I see with your project (although it's nice to mutualize shared code) is the lack of GPU support.

**Comment by heckflosse** [comment]
@aurelienpierre Imho it is not a duplicate. Our current intention is to make the algorithms easier usable for other image processors than RT. At least at the moment I do not intend to make new implementations of the algorithms.

**Comment by aurelienpierre** [comment]
I think Halide have all-purpose filters like gaussian blur and such. That was my point. 

But the multiplication of architectures and libs makes it hard to settle for one strategy or the other.

**Comment by CarVac** [comment]
It doesn't have premade filters as far as I'm aware. You have to code them yourself.
