### ISSUE TITLE
clang error with hpdh.cc

### ISSUE THREAD

**Issue by Benitoite** [CarVac/librtprocess#42]
I'm getting an argument # mismatch in apple clang compilation with the calls to hphd_vertical and hphd_horizontal.

I can compile with these changes:
```
diff --git a/src/demosaic/hphd.cc b/src/demosaic/hphd.cc
index 68890db..92c9e8f 100644
--- a/src/demosaic/hphd.cc
+++ b/src/demosaic/hphd.cc
@@ -349,7 +349,7 @@ rpError hphd_demosaic(int width, int height, const float * const *rawData, float
         }
     }
 #else
-    rc = hphd_vertical(hpmap, 0, W, H);
+    rc = hphd_vertical(rawData, hpmap, 0, W, H);
 #endif
 
     if (!rc) {
@@ -376,7 +376,7 @@ rpError hphd_demosaic(int width, int height, const float * const *rawData, float
             }
         }
 #else
-        rc = hphd_horizontal(hpmap, 0, H);
+        rc = hphd_horizontal(rawData, hpmap, 0, 0, H);
 #endif
         if (!rc) {
             setProgCancel(0.43);
```

**Comment by heckflosse** [comment]
@Benitoite Thanks for reporting. I will fix that.
Why does apple clang try to build without OpenMp?

**Comment by Benitoite** [comment]
I think i might have called cmake with flags for apple clang 10 on apple clang 9, which is not the right way to go about things (usually i have to use clang++-mp-3.9 instead of apple clang 9, or compile on macOS 10.14 with apple clang 10, which can preprocess openmp).
