### ISSUE TITLE
add -ftree-vectorize

### ISSUE THREAD

**Issue by heckflosse** [CarVac/librtprocess#45]
When making a `RelWithDebinfo` build, some functions get quite slow because `-ftree-vectorize` is not included in `-O2`

@cryptomilk What's the cleanest way to add this flag?

**Comment by darix** [comment]
https://cmake.org/cmake/help/v3.0/module/CheckCXXCompilerFlag.html

**Comment by cryptomilk** [comment]
Add it to https://github.com/CarVac/librtprocess/blob/master/CompilerChecks.cmake ??

**Comment by heckflosse** [comment]
@cryptomilk Andreas, thanks for having a look :+1:
