### ISSUE TITLE
Add MSVC support?

### ISSUE THREAD

**Issue by JVision** [CarVac/librtprocess#48]
Hi CarVac, 
This is a super useful project for people dealing with the raw sensor data. Like a sunshine into the dark world. 
would appreciate if this could be easily built under MSVC.

**Comment by CarVac** [comment]
I am entirely unfamiliar with MSVC. What changes might it need to work with it?

**Comment by JVision** [comment]
MSVC does not support openmp 4.0 or implicit conversion between simd types. that's the major difference. I can help on that part. how can I contribute?  maybe a new pull request?

**Comment by CarVac** [comment]
If you know what to change and how to do it cleanly, a pull request would work.

We should probably bring in @heckflosse who is the most familiar with what is going on with the vector intrinsics and OpenMP used in the RawTherapee code this came from.

**Comment by JVision** [comment]
Yes. I do. though, I won't claim to be an expert on SIMD and OpenMP. I guess at the very beginning, most of the work is just to write a few #pragma derivative to tell the compiler not to use the unsupported features of openmp when it detects the compiler is MSVC. For the opemp stuff, at the begenning we could also write explicit type conversion, easier to read as well. Does this sound Ok to you?

**Comment by heckflosse** [comment]
@JVision 
> maybe a new pull request?

Yes, please.

**Comment by JVision** [comment]
@heckflosse will do!

**Comment by emruiz81** [comment]
I know it's been a while, but this is now fixed in PR #74  and #75
