### ISSUE TITLE
Build the shared library optionally

### ISSUE THREAD

**Issue by Vincent-FA** [CarVac/librtprocess#53]
There is an option to build the static library, but the shared library is always built now. Would it be possible to deactivate the build of the shared library with an option? I don't need it and it takes a long time to compile. Thank you

**Comment by Vincent-FA** [comment]
I actually found a simple way, specifying the target instead of using the default `all`:
```
$ make rtprocess_static
```

So maybe nothing more is required.

**Comment by CarVac** [comment]
Is that all that's required to make a static build? Or is there a cmake flag? I'm far from an expert on building.

If you'd like, I could add instructions to the readme.

**Comment by Vincent-FA** [comment]
It can be useful to document it indeed, I got the info privately: `-DWITH_STATIC_LIB=ON` must be passed to cmake to activate the build of the static library.
